### ISSUE TITLE
SQL error after installation

### ISSUE THREAD

**Issue by seirerman** [smichaelsen/typo3-page-warmup#1]
During a test of the staticfilecache extension I had to look for alternatives to the crawler and cachemgm extensions, as they are not compatible with staticfilecache.
[lochmueller/seocli](https://github.com/lochmueller/seocli) can warm up the cache initially, and typo3-page-warmup should cover the re-caching of edited pages.

So I tried to install your extension via composer, which didn't work because it's not yet on packagist.org.

After copying the extension manually (which created other issues of its own, such as the name of the extension directory (typo3-page-warmup? page_warmup?) or not being able to uninstall the extension in the extension manager because of "UnexpectedValueException: The package "typo3-page-warmup" depends on "typo3/cms-core" which is not present in the system.") and registering the classes in composer.json, I installed it in the extension manager and created a new scheduler task. That was when I noticed that the tables from ext_tables.sql are missing.

This is the error I got:
![image](https://user-images.githubusercontent.com/1758587/174810550-42f5e76f-eae8-407e-b672-c238ae8a1487.png)
cache_tag is also affected.

I was able to fix it by adding the key length:
```
CREATE TABLE tx_pagewarmup_reservation (
	cache tinytext NOT NULL,
	url text NOT NULL,
	cache_tag tinytext NOT NULL,
	KEY cache_tag (cache(191),cache_tag(191))
);

CREATE TABLE tx_pagewarmup_queue (
	url text NOT NULL,
	done tinyint(4) DEFAULT '0' NOT NULL,
	queued int(11) DEFAULT '0' NOT NULL,
	UNIQUE url (url(191))
);
```
After applying that patch the extension and the scheduler task worked. The cache files for staticfilecache were also written.

**Comment by smichaelsen** [comment]
@seirerman thanks, would you mind creating a MR?

**Comment by seirerman** [comment]
Sure. Can't do much about the composer issue, though.

**Comment by smichaelsen** [comment]
The package is on https://packagist.org/packages/smic/page-warmup

`composer require smic/page-warmup` - I'll add that to the readme
