### ISSUE TITLE
Too many queue entries?

### ISSUE THREAD

**Issue by seirerman** [smichaelsen/typo3-page-warmup#2]
Edit a content element (tt_content) on a page: Only that page gets added to the queue, which is fine.
Edit the page properties of a page results in all (!) pages being added to the queue. Even pages from other branches that have no direct connection to that page.

Is that intended? I guess on bigger sites with lots of changes by editors this would cause a lot of CPU load.

**Comment by smichaelsen** [comment]
`page_warmup` only adds pages to the queue that really have been flushed from the cache (if you experience something different, open a bug for that). So if you get more queue entries than you expect, check your caching configuration (e.g. look out for `TCEMAIN.clearCache_pageGrandParent = 1`).
